stages:
  - deploy_todev
  - deploy_staging
  - deploy_production

deploy_todev:
  stage: deploy_todev
  script:
      - cd /var/www/pro
      - sudo git checkout dev && sudo git pull
      
  tags:
      - dev
  only:
      - dev

deploy_staging:
  stage: deploy_staging
  script:
      - id
      - sudo mysqldump -uroot takedaph_pro | gzip > /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz
      - sudo scp /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz deploy@stage.takeda.antosh.co:/tmp/
      - sudo ssh deploy@stage.takeda.antosh.co 'zcat /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz | sudo mysql -utakedaph_pro -pfjfa9oSU takedaph_pro'
      - sudo ssh deploy@stage.takeda.antosh.co 'cd /mnt/www/wwwnew/pro && sudo git checkout staging && sudo git pull  origin staging'
      - sudo ssh deploy@stage.takeda.antosh.co 'sudo cat /home/deploy/pro_settings.php > /mnt/www/wwwnew/pro/web/sites/default/settings.php'
      - sudo ssh deploy@stage.takeda.antosh.co 'cd /mnt/www/wwwnew/pro && sudo drush cr'

  tags:
      - dev
  only:
      - staging


deploy_production:
  stage: deploy_production
  script:
      - id
      - sudo mysqldump -utakedaph_pro -pfjfa9oSU takedaph_pro | gzip > /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz
      - scp /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz takedaph@sl350.web.hostpoint.ch:/tmp/
      - ssh takedaph@sl350.web.hostpoint.ch 'zcat /tmp/takedaph_pro_$(date +%Y-%m-%d).sql.gz | mysql -utakedaph_pro -pfjfa9oSU -htakedaph.mysql.db.internal takedaph_pro'
      - ssh takedaph@sl350.web.hostpoint.ch 'cd /home/takedaph/www/wwwnew/pro && git checkout master && git pull'
      - ssh takedaph@sl350.web.hostpoint.ch 'cd /home/takedaph/www/wwwnew/pro && /home/takedaph/.composer/vendor/bin/drush cr'
  tags:
      - staging
  only:
      - master
